_common: !include "../shared.yaml"

name: geopolitik-backend
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - aeson
    - base
    - bytestring
    - cookie
    - cryptonite
    - directory
    - exceptions
    - geojson
    - mtl
    - http-api-data
    - optparse-applicative
    - postgresql-simple
    - random
    - servant-client
    - servant-client-core
    - servant-js
    - servant-server
    - text
    - time
    - transformers
    - unix
    - unordered-containers
    - uuid
    - wai
    - wai-extra
    - warp
  <<: *library

executables:
  geopolitik-backend:
    main: 'app/Entry.hs'
    dependencies:
      - geopolitik-backend
    <<: *executable
  drop:
    main: 'app/Drop.hs'
    dependencies:
      - base
      - exceptions
      - geopolitik-backend
      - mtl
      - postgresql-simple
      - time
      - transformers
      - unix
    <<: *executable
  migrate:
    main: 'app/Migrate.hs'
    dependencies:
      - base
      - exceptions
      - geopolitik-backend
      - mtl
      - postgresql-simple
      - time
      - transformers
      - unix
    <<: *executable
  docs:
    main: 'app/Docs.hs'
    dependencies:
      - base
      - bytestring
      - cookie
      - geopolitik-backend
      - lens
      - mtl
      - servant-client
      - servant-docs
      - servant-server
      - text
      - time
      - transformers

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - geopolitik-backend
    <<: *test
