_common: !include "../shared.yaml"

name: geopolitik
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - servant-docs
    - cryptonite
    - warp
    - aeson
    - cookie
    - wai
    - random
    - uuid
    - exceptions
    - servant-server
    - mtl
    - transformers
    - unordered-containers
    - postgresql-simple
    - hashable
    - bytestring
    - text
    - time
    - base
  <<: *library

executables:
  drop:
    main: 'app/Drop.hs'
    dependencies:
      - geopolitik
      - postgresql-simple
      - mtl
      - transformers
      - base
      - time
      - exceptions
    <<: *executable
  geopolitik:
    main: 'app/Entry.hs'
    dependencies:
      - geopolitik
    <<: *executable
  migrate:
    main: 'app/Migrate.hs'
    dependencies:
      - time
      - exceptions
      - postgresql-simple
      - mtl
      - transformers
      - geopolitik
      - base
    <<: *executable
  apidocs:
    main: 'app/Docs.hs'
    dependencies:
      - cookie
      - servant-server
      - time
      - text
      - geopolitik
      - base
      - servant-docs
      - servant

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - geopolitik
    <<: *test
