_common: !include "../shared.yaml"

name: geopolitik
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - warp
    - aeson
    - cookie
    - wai
    - random
    - uuid
    - exceptions
    - servant-server
    - mtl
    - transformers
    - unordered-containers
    - postgresql-simple
    - hashable
    - bytestring
    - text
    - time
    - base
  <<: *library

executables:
  geopolitik:
    main: Entry.hs
    source-dirs: app
    dependencies:
      - geopolitik
    <<: *executable

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - geopolitik
    <<: *test
