_common: !include "../shared.yaml"

name: geopolitik-api
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - unordered-containers
    - postgresql-simple
    - hashable
    - bytestring
    - text
    - time
    - base
  <<: *library

executables:
  exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - geopolitik-api
    <<: *executable

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - geopolitik-api
    <<: *test
