_common: !include "../shared.yaml"

name: geopolitik
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - exceptions
    - servant-server
    - mtl
    - transformers
    - unordered-containers
    - postgresql-simple
    - hashable
    - bytestring
    - text
    - time
    - base
  <<: *library

executables:
  migrate:
    main: Migrate.hs
    source-dirs: app
    dependencies:
      - transformers
      - mtl
      - exceptions
      - time
      - text
      - bytestring
      - postgresql-simple
      - geopolitik
    <<: *executable

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - geopolitik
    <<: *test
